"""LearnForge support assistant — M1 ingestion + M2 retrieval + M3 evidence assessment."""

from learnforge.embed import (
    DEFAULT_EMBEDDINGS_PATH,
    DEFAULT_MODEL_NAME,
    LocalEmbedder,
    build_embedding_store,
    get_embedder,
    load_embedding_store,
    load_records,
    save_embedding_store,
)
from learnforge.lexical import BM25Index, build_index, tokenize
from learnforge.retrieval import (
    DEFAULT_TOP_K,
    RRF_K,
    RetrievalResult,
    Retriever,
)
from learnforge.evidence import (
    ANSWERABLE,
    ASSESSMENT_STATES,
    CLARIFICATION_REQUIRED,
    CONFIDENCE_HIGH,
    CONFIDENCE_LOW,
    CONFIDENCE_MEDIUM,
    CONFLICTING_EVIDENCE,
    ESCALATION_REQUIRED,
    INSUFFICIENT_EVIDENCE,
    ROUTE_CLARIFY,
    ROUTE_DECLINE,
    ROUTE_ESCALATE,
    ROUTE_GENERATE,
    SECURITY_ESCALATION,
    AmbiguityAssessment,
    ConfidenceAssessment,
    ConflictIndicator,
    CoverageAssessment,
    EscalationAssessment,
    EvidenceAssessment,
    EvidenceItem,
    SecurityAssessment,
    assess_evidence,
)
from learnforge.generation import (
    API_KEY_ENV_VAR,
    DEFAULT_MODEL,
    DEFAULT_PROVIDER,
    PROMPT_VERSION,
    SYSTEM_PROMPT,
    FakeProvider,
    GenerationError,
    GenerationResult,
    GroqProvider,
    LLMProvider,
    MissingAPIKeyError,
    PromptBundle,
    build_prompt,
    extract_citations,
    generate,
    invalid_citations,
    resolve_api_key,
    safe_failure_message,
    strip_invalid_citations,
)
from learnforge.schema import (
    AUTHORITY_BY_TYPE,
    M0_METADATA_KEYS,
    M1_METADATA_KEYS,
    SCHEMA_VERSION,
    SOURCE_TYPES,
    UNDATED,
    Record,
    build_metadata,
    source_type_for_id,
    validate_record,
)

from learnforge.conversation import (
    DEFAULT_MAX_TURNS,
    EmptyMessageError,
    InvalidRoleError,
    Turn,
    Conversation,
    new_conversation,
)

__all__ = [
    # M1 schema + ingestion
    "AUTHORITY_BY_TYPE",
    "M0_METADATA_KEYS",
    "M1_METADATA_KEYS",
    "SCHEMA_VERSION",
    "SOURCE_TYPES",
    "UNDATED",
    "Record",
    "build_metadata",
    "source_type_for_id",
    "validate_record",
    # M2 retrieval
    "DEFAULT_EMBEDDINGS_PATH",
    "DEFAULT_MODEL_NAME",
    "DEFAULT_TOP_K",
    "RRF_K",
    "BM25Index",
    "LocalEmbedder",
    "RetrievalResult",
    "Retriever",
    "build_embedding_store",
    "build_index",
    "get_embedder",
    "load_embedding_store",
    "load_records",
    "save_embedding_store",
    "tokenize",
    # M3 evidence assessment
    "ANSWERABLE",
    "ASSESSMENT_STATES",
    "CLARIFICATION_REQUIRED",
    "CONFIDENCE_HIGH",
    "CONFIDENCE_LOW",
    "CONFIDENCE_MEDIUM",
    "CONFLICTING_EVIDENCE",
    "ESCALATION_REQUIRED",
    "INSUFFICIENT_EVIDENCE",
    "ROUTE_CLARIFY",
    "ROUTE_DECLINE",
    "ROUTE_ESCALATE",
    "ROUTE_GENERATE",
    "SECURITY_ESCALATION",
    "AmbiguityAssessment",
    "ConfidenceAssessment",
    "ConflictIndicator",
    "CoverageAssessment",
    "EscalationAssessment",
    "EvidenceAssessment",
    "EvidenceItem",
    "SecurityAssessment",
    "assess_evidence",
    # M4 grounded generation
    "API_KEY_ENV_VAR",
    "DEFAULT_MODEL",
    "DEFAULT_PROVIDER",
    "PROMPT_VERSION",
    "SYSTEM_PROMPT",
    "FakeProvider",
    "GenerationError",
    "GenerationResult",
    "GroqProvider",
    "LLMProvider",
    "MissingAPIKeyError",
    "PromptBundle",
    "build_prompt",
    "extract_citations",
    "generate",
    "invalid_citations",
    "resolve_api_key",
    "safe_failure_message",
    "strip_invalid_citations",
    # M5 conversation context
    "DEFAULT_MAX_TURNS",
    "EmptyMessageError",
    "InvalidRoleError",
    "Turn",
    "Conversation",
    "new_conversation",
]
